import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { adminSupportRequest } from '@/services/api'
import { PageHeader, SearchField, StatusBadge, EmptyState } from '@/components/admin/AdminUi'
import { SUPPORT_CATEGORIES, SUPPORT_PRIORITIES, SUPPORT_STATUSES } from '@/services/support'

export default function AdminSupport() {
  const [tickets, setTickets] = useState([])
  const [q, setQ] = useState('')
  const [status, setStatus] = useState('all')
  const [category, setCategory] = useState('all')
  const [priority, setPriority] = useState('all')
  const [loading, setLoading] = useState(true)
  useEffect(() => { adminSupportRequest().then(setTickets).catch(() => setTickets([])).finally(() => setLoading(false)) }, [])
  const filtered = useMemo(() => { const query = q.toLowerCase().trim(); return tickets.filter((ticket) => { const hay = `${ticket.ticket_number} ${ticket.subject} ${ticket.order_id || ''} ${ticket.user_id || ''}`.toLowerCase(); return (!query || hay.includes(query)) && (status === 'all' || ticket.status === status) && (category === 'all' || ticket.category === category) && (priority === 'all' || ticket.priority === priority) }) }, [tickets, q, status, category, priority])
  return <div><PageHeader eyebrow="Customer care" title="Support tickets" subtitle="Review customer issues, update ownership and reply from one workspace." /><div className="mt-6 flex flex-wrap gap-3"><SearchField value={q} onChange={setQ} placeholder="Search ticket, customer, order ID" /><select value={status} onChange={(e) => setStatus(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="all">All statuses</option>{SUPPORT_STATUSES.map((item) => <option key={item}>{item}</option>)}</select><select value={category} onChange={(e) => setCategory(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="all">All categories</option>{SUPPORT_CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select><select value={priority} onChange={(e) => setPriority(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="all">All priorities</option>{SUPPORT_PRIORITIES.map((item) => <option key={item}>{item}</option>)}</select></div>{!loading && !filtered.length ? <div className="mt-6"><EmptyState title="No support tickets" hint="Tickets raised by customers will appear here." /></div> : <div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Ticket</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Subject</th><th className="px-4 py-3">Order</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Priority</th><th className="px-4 py-3">Status</th><th /></tr></thead><tbody>{filtered.map((ticket) => <tr key={ticket.id} className="border-b border-slate-100"><td className="px-4 py-3 font-mono text-xs font-bold text-emerald-700">{ticket.ticket_number}</td><td className="px-4 py-3"><p className="font-semibold">{ticket.customer?.name || 'Customer'}</p><p className="text-xs text-slate-400">{ticket.customer?.email || ticket.user_id}</p><p className="text-xs text-slate-400">{ticket.customer?.phone || ''}</p></td><td className="px-4 py-3"><p className="font-semibold">{ticket.subject}</p><p className="text-xs text-slate-400">{new Date(ticket.updated_at).toLocaleString('en-IN')}</p></td><td className="px-4 py-3 font-mono text-xs">{ticket.order_id ? String(ticket.order_id).slice(0, 8) : '—'}</td><td className="px-4 py-3 text-xs">{ticket.category}</td><td className="px-4 py-3"><StatusBadge value={ticket.priority} /></td><td className="px-4 py-3"><StatusBadge value={ticket.status} /></td><td className="px-4 py-3 text-right"><Link to={`/admin/support/${ticket.id}`} className="font-semibold text-emerald-700">Open</Link></td></tr>)}</tbody></table></div>}</div>
}
